name: Deploy

on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: List all available xcode versions
      run: ls /Applications | grep Xcode
    - name: Decrypt large secret
      run: provisioning/import_provisioning.sh
      env: 
        PROVISIONING_PASSWORD: ${{ secrets.provisioning_password }}
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app && /usr/bin/xcodebuild -version
    - name: Create Archive archive path
      run: mkdir ~/Desktop/temp
    - name: Build
      run: xcodebuild -scheme Hotstar -allowProvisioningUpdates build
    - name: Archive
      run: xcodebuild -scheme Hotstar -archivePath ~/Desktop/temp -allowProvisioningUpdates archive
    - name: Export
      run: xcodebuild -allowProvisioningUpdates -exportArchive -archivePath ~/Desktop/temp -exportPath DerivedData/ipa -exportOptionsPlist Profiles/appstore.plist