name: Upload

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Execute the shell script
      run: ./scripts/upload.sh
