name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Version
      run: sudo xcode-select -switch /Applications/Xcode.app && /usr/bin/xcodebuild -version
    - name: Execute the shell script
      run: ./scripts/version_bump.sh